<?xml version="1.0" encoding="utf-8"?><Database Name="FuelDB" Class="FuelDbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=HGF80-KL89;Initial Catalog=FuelDB;User ID=User" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="FuelDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TXN" Member="TXNs">
    <Type Name="TXN">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TillCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(15,2) NOT NULL" CanBeNull="false" />
      <Column Name="PlateNo" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="TransactionId" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="OperatorName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TransactionEndFuel" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="InsertDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="InsertUser" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="UpdateUser" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
</Database>